# order parameter lists positions in array
DATE_TIME_LIST_ARRAY_INDEX = 0
STATUS_LIST_ARRAY_INDEX = 1
DESCRIPTION_LIST_ARRAY_INDEX = 2
TAG_LIST_ARRAY_INDEX = 3
DIRECTION_LIST_ARRAY_INDEX = 4
ID_LIST_ARRAY_INDEX = 5
INITIAL_VOLUME_LIST_ARRAY_INDEX = 6
FILL_VOLUME_LIST_ARRAY_INDEX = 7
CURRENCY_PAIR_LIST_ARRAY_INDEX = 8
INITIAL_PX_LIST_ARRAY_INDEX = 9
FILL_PX_LIST_ARRAY_INDEX = 10
# order parameter lists positions in array

# order parameters positions in array
IDENTIFIER_ARRAY_INDEX = 0
STATUS_ARRAY_INDEX = 1
DATE_TIME_ARRAY_INDEX = 2
DIRECTION_ARRAY_INDEX = 3
TAG_ARRAY_INDEX = 4
DESCRIPTION_ARRAY_INDEX = 5
CURRENCY_PAIR_ARRAY_INDEX = 6
INITIAL_PX_ARRAY_INDEX = 7
FILL_PX_ARRAY_INDEX = 8
INITIAL_VOLUME_ARRAY_INDEX = 9
FILL_VOLUME_ARRAY_INDEX = 10
# order parameters positions in array

# other
SECOND_TO_MICROSECOND_CONVERTING_COEF = 1000
NULL = 'NULL'
# other
