STATUS_NEW = "New"
STATUS_TO_PROVIDER = "To provider"
STATUS_REJECTED = "Rejected"
STATUS_FILLED = "Filled"
STATUS_PARTIAL_FILLED = "Partial filled"
FINAL_STATUSES = [STATUS_REJECTED, STATUS_FILLED, STATUS_PARTIAL_FILLED]
FINAL_STATUSES_NUMBER = 3
