DEFAULT_CONFIG_FILES_PATH = "/home/viacheslav/PycharmProjects/DataGenerator/config/config_files/"
DEFAULT_CONFIG_FILES_EXTENSION = ".ini"
DEFAULT_CONFIG_FILES = [
	DEFAULT_CONFIG_FILES_PATH + "config_currency" + DEFAULT_CONFIG_FILES_EXTENSION,
	DEFAULT_CONFIG_FILES_PATH + "config_database" + DEFAULT_CONFIG_FILES_EXTENSION,
	DEFAULT_CONFIG_FILES_PATH + "config_date" + DEFAULT_CONFIG_FILES_EXTENSION,
	DEFAULT_CONFIG_FILES_PATH + "config_description" + DEFAULT_CONFIG_FILES_EXTENSION,
	DEFAULT_CONFIG_FILES_PATH + "config_digit" + DEFAULT_CONFIG_FILES_EXTENSION,
	DEFAULT_CONFIG_FILES_PATH + "config_file" + DEFAULT_CONFIG_FILES_EXTENSION,
	DEFAULT_CONFIG_FILES_PATH + "config_log" + DEFAULT_CONFIG_FILES_EXTENSION,
	DEFAULT_CONFIG_FILES_PATH + "config_order" + DEFAULT_CONFIG_FILES_EXTENSION,
	DEFAULT_CONFIG_FILES_PATH + "config_message_broker" + DEFAULT_CONFIG_FILES_EXTENSION,
	DEFAULT_CONFIG_FILES_PATH + "config_tag" + DEFAULT_CONFIG_FILES_EXTENSION
]
