# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_record.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import generator.order.entities.order_pb2 as order__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='order_record.proto',
  package='mapping',
  syntax='proto3',
  serialized_pb=_b('\n\x12order_record.proto\x12\x07mapping\x1a\x0border.proto\"O\n\x0bOrderRecord\x12\x1d\n\x05order\x18\x01 \x01(\x0b\x32\x0e.mapping.Order\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x62\x06proto3')
  ,
  dependencies=[order__pb2.DESCRIPTOR,])




_ORDERRECORD = _descriptor.Descriptor(
  name='OrderRecord',
  full_name='mapping.OrderRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order', full_name='mapping.OrderRecord.order', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='mapping.OrderRecord.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='mapping.OrderRecord.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=123,
)

_ORDERRECORD.fields_by_name['order'].message_type = order__pb2._ORDER
DESCRIPTOR.message_types_by_name['OrderRecord'] = _ORDERRECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderRecord = _reflection.GeneratedProtocolMessageType('OrderRecord', (_message.Message,), dict(
  DESCRIPTOR = _ORDERRECORD,
  __module__ = 'order_record_pb2'
  # @@protoc_insertion_point(class_scope:mapping.OrderRecord)
  ))
_sym_db.RegisterMessage(OrderRecord)


# @@protoc_insertion_point(module_scope)
