SECOND_TO_MICROSECOND_CONVERTING_COEF = 1000
NULL = 'NULL'
NUMBER_OF_RECONNECTS = 3
RECONNECT_TIMEOUT = 3
ORDER_RECORD_STRING_DELIMETER = ","
REPORT_OUTPUT_FILE = 'FILE'
REPORT_OUTPUT_CONSOLE = 'CONSOLE'
STORAGE_TO_DB_WRITER_CYCLE_WORK_TIME = 2
